# This SRX task configures a host, service and allows access to the host running the service
- name: Generate and Deploy Service Access Configuration to vsrx gateway
  hosts: vsrx
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    ansible_python_interpreter: "/Users/john/vsrx/.env/bin/python"
  tasks:
    - name: deploy service access config
      template: src=vsrx.conf.s2 dest=/tmp/{{ inventory_hostname }}.conf

    - name: Display all variables/facts known for a host
      debug: var=hostvars[inventory_hostname]

    - name: Deploy config to device ... please wait
      junos_install_config:
        host={{ ansible_ssh_host }}
        port={{ ansible_ssh_port }}
        user={{ ansible_user }}
        file=/tmp/{{ inventory_hostname }}.conf
        overwrite=yes
        replace=no
        logfile=/tmp/changes.log

    - name: Checking NETCONF connectivity
      wait_for: host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} timeout=5
